---
- name: "Deploy GLPI cron locally using Podman"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true

  pre_tasks:
    - name: "Include project default vars"
      ansible.builtin.include_vars: "{{ file_to_include }}"
      loop:
        - vars/main.yaml
      loop_control:
        loop_var: file_to_include

  tasks:
    - name: "Start GLPI cron"
      containers.podman.podman_container:
        name: "{{ pod_name }}_cron"
        image: "localhost/{{ pod_name }}_cron"
        pod: "{{ pod_name }}"
        state: started
        user: 33
        group_add:
          - 33
        volumes_from: 
          - "{{ pod_name }}_init"
...
