---
- name: "Deploy GLPI cron locally using Podman"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true

  pre_tasks:
    - name: "Include project default vars"
      ansible.builtin.include_vars: "{{ file_to_include }}"
      loop:
        - vars/main.yaml
      loop_control:
        loop_var: file_to_include

    - name: "Get version"
      ansible.builtin.shell: |
        jq -r '(.major | tostring) + "." + (.minor | tostring) + "." + (.patch | tostring) + if .snapshot then "-SNAPSHOT" else "" end' ../../../version.json
      register: current_version_reg

    - name: "Set version"
      ansible.builtin.set_fact:
        glpi_version: current_version_reg.stdout

  tasks:
    - name: "Start GLPI cron"
      containers.podman.podman_container:
        name: "{{ pod_name }}_cron"
        image: "localhost/{{ pod_name }}_cron:{{ glpi_version }}"
        pod: "{{ pod_name }}"
        state: started
        user: 33
        group_add:
          - 33
        volumes_from: 
          - "{{ pod_name }}_init"
...
