---
- name: "Prepare GLPI database"
  ansible.builtin.import_playbook: prepare-database.yaml

- name: "Prepare GLPI environment"
  ansible.builtin.import_playbook: deploy-glpi-init.yaml

- name: "Deploy GLPI locally using Podman"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true

  pre_tasks:
    - name: "Include project default vars"
      ansible.builtin.include_vars: "{{ file_to_include }}"
      loop: 
        - ../../defaults/main.yaml
        - defaults/main.yaml
      loop_control:
        loop_var: file_to_include

  tasks:
    - name: "Start GLPI"
      containers.podman.podman_container:
        name: "{{ image_prefix }}_web"
        image: "localhost/{{ image_prefix }}_web"
        pod: "{{ pod_name }}"
        state: started
        user: 33
        group_add:
          - 33
        volumes_from: 
          - "{{ image_prefix }}_init"

...
