---
- name: "Undeploy local GLPI Podman deployment"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true

  pre_tasks:
    - name: "Include project default vars"
      ansible.builtin.include_vars: "{{ file_to_include }}"
      loop:
        - ../defaults/main.yaml
        - defaults/main.yaml
      loop_control:
        loop_var: file_to_include

  tasks:
    - name: "Delete POD"
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        state: absent

    - name: "Delete glpi volumes"
      containers.podman.podman_volume:
        name: "{{ volume_to_delete }}"
        state: absent
      loop:
        - trikorasolns_glpi_glpi_var
        - trikorasolns_glpi_glpi_etc
        - trikorasolns_glpi_db
      loop_control:
        loop_var: volume_to_delete

...
