---
- name: "Deploy Grafana"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true

  pre_tasks:
    - name: "Include project default vars"
      ansible.builtin.include_vars: "{{ file_to_include }}"
      loop:
        - defaults/main.yaml
        - vars/main.yaml
      loop_control:
        loop_var: file_to_include

    # - name: Check the Trikora Helm Chart folder variable is defined
    #   assert:
    #     that:
    #       - "trikora_helm_project_dir is defined"
    #     msg:
    #       - "Please specify the Trikora Helm Chart folder variable ('trikora_helm_project_dir')"

  tasks:

    - name: "Deploy grafana on k8s"
      kubernetes.core.k8s:
        state: present
        src: "{{ grafana_k8s_yaml_file }}"
      loop:
        - ../grafana/templates/10-configmap.yaml
        - ../grafana/templates/15-secret.yaml
        - ../grafana/templates/20-deployment.yaml
        - ../grafana/templates/30-service.yaml
        - ../grafana/templates/40-ingress.yaml
      loop_control:
        loop_var: grafana_k8s_yaml_file

    # - name: Wait until grafana is available
    #   ansible.builtin.wait_for:
    #     host: grafana.twm.svc.cluster.local
    #     port: 80
    #     delay: 10
    #     state: drained

    - name: Wait until grafana is available
      uri:
        url: 'http://grafana.twm.svc.cluster.local/'
        return_content: yes
        validate_certs: no
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
      delay: 5 # Every 5 seconds
      register: uri_output

    - name: "Load the organization"
      ansible.builtin.shell: |
        ./src/main/grafana/load_init_config_kind.sh

...
