---
- name: "Deploy PHP My Admin"
  hosts: "{{ target_host | default('localhost') }}"
  gather_facts: true

  pre_tasks:
    - name: "Include project default vars"
      ansible.builtin.include_vars: "{{ file_to_include }}"
      loop:
        - defaults/main.yaml
        - vars/main.yaml
      loop_control:
        loop_var: file_to_include

    # - name: Check the Trikora Helm Chart folder variable is defined
    #   assert:
    #     that:
    #       - "trikora_helm_project_dir is defined"
    #     msg:
    #       - "Please specify the Trikora Helm Chart folder variable ('trikora_helm_project_dir')"

    - name: "Check the Trikora Helm Chart folder variable is defined"
      assert:
        that:
          - "trikora_helm_project_dir is defined"
        msg:
          - "Please specify the Trikora Helm Chart folder variable ('trikora_helm_project_dir')"

  tasks:

    - name: "Deploy PHP My Admin using Helm Chart"
      kubernetes.core.helm:
        name: phpmyadmin
        chart_ref: "{{ trikora_helm_project_dir }}/phpmyadmin"
        release_namespace: "{{ k8s_namespace }}"
        wait: true
        replace: true
        values_files:
          - "../helm-charts/helm-phpmyadmin-values.yaml"
      register: phpmyadmin_helm_res

...
